<?php $title = "Profile" ?>

<?php ob_start() ?>
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
<?php $top_js = ob_get_clean() ?>

<?php ob_start() ?>

<div x-data="data">
    <section class="bg-Profile banner-section all-sub-banner profile-new">
        <div class="page-header-overlay">
            <div class="container container-profile">

                <div class="profile-user-all">
                    <div class="profile-img-left">
                        <img src="<?php echo $user->avatar ? storage()->url($user->avatar) : assets('Assets/images/profile/avatar.png') ?>"
                            alt="single-profile-img-1" class="img-responsive">
                    </div>
                    <div class="user-pr-details">
                        <h3 class="pt-3"><?php echo $user->name ?></h3>
                        <p class="mb-0">
                            <?php echo $user->email ?> ,<?php echo $user->phone ?>
                        </p>

                    </div>
                </div>
            </div>
            <!-- .container -->
        </div>
        <!-- .page-header-overlay -->
    </section>
    <!-- contact-request-end TAB -->
    <div class="tab-pane fade show active"
        id="blogs-tab-pane" role="tabpanel" aria-labelledby="blogs-tab" tabindex="0">
        <template x-if="!blog_edit">
            <div class="row w-100">
                <h3 class="mb-4"> Upload Blog </h3>
                <div class="single-profile-upload bg-cate-all pt-3">
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <label class="form-label"><strong>Blog Category:</strong></label>
                            <select x-model="blog.category_id" class="form-control"
                                name="category_id" id="category">
                                <option value="">Select a Category</option>
                                <template x-for="(category,index) in categories">
                                    <option :value="category.id"
                                        :selected="category.id == blog.category_id"
                                        x-text="category.name">
                                    </option>
                                </template>
                            </select>

                            <span x-show="getError('category_id')" class="text-danger"><i
                                    class="fa-solid fa-circle-exclamation me-1"></i><span
                                    x-text="getError('category_id')"></span></span>
                        </div>

                        <div class="col-md-6">
                            <label class="form-label"><strong>Blog Title:</strong></label>
                            <input class="form-control" type="text" name="title"
                                x-model="blog.title" placeholder="Title">
                            <span x-show="getError('title')" class="text-danger"><i
                                    class="fa-solid fa-circle-exclamation me-1"></i><span
                                    x-text="getError('title')"></span></span>
                        </div>

                    </div>

                    <div class="row mt-2">
                        <div class="col-12 editor-custom">
                            <label class="form-label"><strong>Blog Description:</strong></label>
                            <div id="editor" x-model="blog.description" x-ref="description"
                                x-init="ClassicEditor
                                                            .create($refs.description, {
                                                                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
                                                            })
                                                            .then(editor => {
                                                                window.editor = editor;
                                                            })
                                                            .catch(err => {
                                                                console.log(document.querySelector('#editor'))
                                                                console.error(err.stack);
                                                            })">

                            </div>
                        </div>
                        <div class="col-12">
                            <span x-show="getError('description')" class="text-danger"><i
                                    class="fa-solid fa-circle-exclamation me-1"></i><span
                                    x-text="getError('description')"></span></span>
                        </div>
                    </div>
                    <template x-if="blog.file">

                        <div class="row mt-2">
                            <template
                                x-if="blog.file_type=='jpeg'||blog.file_type=='png'||blog.file_type=='jpg'">
                                <div class="col-md-12">
                                    <img :src="blog.file"
                                        alt="single-profile-img-1 img-upload"
                                        class="img-responsive img-upload">
                                </div>
                            </template>

                            <template x-if="blog.file_type=='mp4'">
                                <video controls autoplay>
                                    <source :src="blog.file" type="video/mp4">
                                </video>
                            </template>

                            <template x-if="blog.file_type=='pdf'">
                                <embed :src="blog.file" type="application/pdf"
                                    width="100%" height="600px" />
                            </template>
                        </div>

                    </template>

                    <div class="">
                        <hr class="mb-0 border-dashed-all">
                    </div>
                    <div class="row m-0 bg-gray-up">
                        <div class="col-3 upload-list text-center block-up bb-res">
                            <div action="" class="file-upload">
                                <input type="file"
                                    @change="setPreview(blog,$event.target.files)" id="img"
                                    name="img" accept="image/*" style="display: none;">
                                <i class="fa-solid fa-photo-film"></i>
                                <label for="img">Photo</label>
                            </div>
                        </div>
                        <div
                            class="col-3 upload-list  border-left-right-dashed text-center block-up borb-rer">
                            <div action="" class="file-upload text-danger">
                                <input type="file"
                                    @change="setPreview(blog,$event.target.files)" id="video"
                                    name="video" accept="video/*" style="display: none;">
                                <i class="fa-solid fa-video"></i>
                                <label for="video">Video</label>
                            </div>
                        </div>
                        <div
                            class="col-3 upload-list border-left-right-dashed border-start-0 text-center block-up brbre-regis">
                            <div class="file-upload">
                                <input type="file"
                                    @change="setPreview(blog,$event.target.files)" id="file"
                                    name="file" accept=".pdf" style="display: none;">
                                <i class="fa-solid fa-file-lines "></i>
                                <label for="file">Article Upload </label>
                            </div>
                        </div>
                        <div class="col-3 text-center  border-r-round w50a">
                            <div class="btn-group btn-all-group res-icon-area" role="group"
                                aria-label="Basic mixed styles example">
                                <button @click="store(true)" type="button"
                                    class="btn btn-success res-icon pde-regis" title="Draft"><i
                                        class="fa-solid fa-file-text me-1"></i>Draft</button>
                                <button @click="store(false)" type="button"
                                    class="btn btn-success res-icon pde-regis" title="Submit"><i
                                        class="fa-solid fa-location-arrow me-1"></i>Submit</button>
                            </div>



                        </div>
                        <div class="col-12 positionrl">
                            <span x-show="getError('file_upload')" class="text-danger error-ab"><i
                                    class="fa-solid fa-circle-exclamation me-1"></i><span
                                    x-text="getError('file_upload')"></span></span>
                        </div>
                    </div>
                </div>
            </div>

        </template>

        <div class="row m-0 m-0-blog">

            <template x-for="(single_blog,index) in blogs" :key="index">
                <div class="col-md-6">
                    <div class="single-profile-item Upload-info bg-white">
                        @if ($user->isMember() && $member->id == $user->member->id)
                        <div class="text-end border-bottom-pr mb-2 pb-2 btn-group-profile">
                            <button class="btn btn-info text-white floa-left-btn"
                                x-text="single_blog.status"></button>
                            <div class="btn-group" role="group"
                                aria-label="Basic mixed styles example">

                                <button
                                    x-show="(!blog_edit || (blog_edit && blog_edit!=single_blog.slug)) && single_blog.status=='Draft'"
                                    class="btn btn-info text-white"
                                    @click="publishBlog(single_blog)"><i
                                        class="fa-solid fa-share me-1"></i>Publish</button>
                                <button
                                    x-show="!blog_edit || (blog_edit && blog_edit!=single_blog.slug)"
                                    @click="blog_edit=single_blog.slug" class="btn btn-warning"><i
                                        class="fa-solid fa-pen-to-square me-1"></i>Edit</button>
                                <button x-show="blog_edit && blog_edit==single_blog.slug"
                                    @click="blog_edit=null" class="btn btn-success"><i
                                        class="fa-solid fa-pen-to-square me-1"></i>Preview</button>
                                <button @click="deleteBlog(single_blog,index)"
                                    class="btn btn-danger"><i
                                        class="fa-solid fa-trash me-1"></i>Delete</button>
                            </div>
                            <!-- <button x-show="(!blog_edit || (blog_edit && blog_edit!=single_blog.slug)) && single_blog.status=='Draft'" class="btn btn-success me-1 btn-sm" @click="publishBlog(single_blog)"><i class="fa-solid fa-share me-1"></i>Publish</button>
                                                                <button x-show="!blog_edit || (blog_edit && blog_edit!=single_blog.slug)" @click="blog_edit=single_blog.slug" class="btn btn-warning me-1 btn-sm"><i class="fa-solid fa-pen-to-square me-1"></i>Edit</button>
                                                                <button x-show="blog_edit && blog_edit==single_blog.slug" @click="blog_edit=null" class="btn btn-warning me-1 btn-sm"><i class="fa-solid fa-pen-to-square me-1"></i>Preview</button>
                                                                <button @click="deleteBlog(single_blog,index)" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash me-1"></i>Delete</button> -->
                        </div>
                        @endif

                        <template x-if="blog_edit && blog_edit==single_blog.slug">
                            <div class="single-profile-upload"
                                style="border: 1px dotted rgba(194, 222, 166, 1);">
                                <div class="row mt-2">
                                    <div class="col-12">
                                        <label class="form-label">Blog Category:</label>
                                        <select x-model="single_blog.category_id" class="form-control"
                                            name="category_id" id="category">
                                            <option value="">Select a Category</option>
                                            <template x-for="(category,index) in categories">
                                                <option
                                                    :selected="category.id == single_blog.category_id"
                                                    :value="category.id" x-text="category.name">
                                                </option>
                                            </template>
                                        </select>
                                    </div>
                                    <div class="col-12">
                                        <span x-show="getError('category_id')" class="text-danger"><i
                                                class="fa-solid fa-circle-exclamation me-1"></i><span
                                                x-text="getError('category_id')"></span></span>
                                    </div>
                                </div>

                                <div class="row mt-2">
                                    <div class="col-12">
                                        <label class="form-label">Blog Title:</label>
                                        <input class="form-control" type="text" name="title"
                                            x-model="single_blog.title" placeholder="Title">
                                    </div>
                                    <div class="col-12">
                                        <span x-show="getError('title')" class="text-danger"><i
                                                class="fa-solid fa-circle-exclamation me-1"></i><span
                                                x-text="getError('title')"></span></span>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-12">
                                        <label class="form-label">Blog Description:</label>
                                        <div x-ref="description" x-init="ClassicEditor
                                                                .create($refs.description, {
                                                                    // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
                                                                })
                                                                .then(editor => {
                                                                    window.editor = editor;
                                                                    editor.setData(single_blog.description)
                                                                })
                                                                .catch(err => {
                                                                    console.log(document.querySelector('#editor'))
                                                                    console.error(err.stack);
                                                                })">

                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <span x-show="getError('description')" class="text-danger"><i
                                                class="fa-solid fa-circle-exclamation me-1"></i><span
                                                x-text="getError('description')"></span></span>
                                    </div>
                                </div>
                                <template x-if="single_blog.file">

                                    <div class="row mt-2">
                                        <template
                                            x-if="single_blog.file_type=='jpeg'||single_blog.file_type=='png'||single_blog.file_type=='jpg'">
                                            <div class="col-12">
                                                <img :src="single_blog.file"
                                                    alt="single-profile-img-1 img-upload"
                                                    class="img-responsive img-upload">
                                            </div>
                                        </template>

                                        <template x-if="single_blog.file_type=='mp4'">
                                            <video controls autoplay>
                                                <source :src="single_blog.file" type="video/mp4">
                                            </video>
                                        </template>

                                        <template x-if="single_blog.file_type=='pdf'">
                                            <embed :src="single_blog.file" type="application/pdf"
                                                width="100%" height="600px" />
                                        </template>
                                    </div>

                                </template>

                                <div class="">
                                    <hr class="mb-0"
                                        style="border-bottom: 1px dotted rgba(194, 222, 166, 1);">
                                </div>
                                <div class="row rowm">
                                    <div class="col-3">
                                        <div action="" class="file-upload">
                                            <input type="file"
                                                @change="setPreview(single_blog,$event.target.files)"
                                                id="img" name="img" accept="image/*"
                                                style="display: none;">
                                            <i class="fa-solid fa-photo-film"></i>
                                            <label for="img">Photo</label>
                                        </div>
                                    </div>
                                    <div class="col-3"
                                        style="border-right: 1px dotted rgba(234, 234, 234, 1);border-left: 1px dotted rgba(234, 234, 234, 1);">
                                        <div action="" class="file-upload text-danger">
                                            <input type="file"
                                                @change="setPreview(single_blog,$event.target.files)"
                                                id="video" name="video" accept="video/*"
                                                style="display: none;">
                                            <i class="fa-solid fa-video"></i>
                                            <label for="video">Video</label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="file-upload">
                                            <input type="file"
                                                @change="setPreview(single_blog,$event.target.files)"
                                                id="file" name="file" accept=".pdf"
                                                style="display: none;">
                                            <i class="fa-solid fa-file-lines "></i>
                                            <label for="file">Article Upload </label>
                                        </div>
                                    </div>
                                    <div class="col-3 dflex-btn">
                                        <div action="" class="file-upload">
                                            <button @click="update(single_blog,true)" type="button"
                                                class="theme-btn btn-style-two btn-send text-warning"><i
                                                    class="fa-solid fa-file-text"></i></button>
                                        </div>
                                        <div action="" class="file-upload">
                                            <button @click="update(single_blog)" type="button"
                                                class="theme-btn btn-style-two btn-send"><i
                                                    class="fa-solid fa-location-arrow"></i></button>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <span x-show="getError('file_upload')" class="text-danger"><i
                                                class="fa-solid fa-circle-exclamation me-1"></i><span
                                                x-text="getError('file_upload')"></span></span>
                                    </div>
                                </div>
                            </div>
                        </template>
                        <template x-if="!blog_edit || blog_edit!=single_blog.slug">
                            <div>
                                <div class="single-profile-img blog-post-details upload-post-pic">

                                    <template
                                        x-if="single_blog.file_type=='jpeg'||single_blog.file_type=='png'||single_blog.file_type=='jpg'">
                                        <img :src="single_blog.file" alt="single-profile-img-1"
                                            class="img-responsive">
                                    </template>

                                    <template x-if="single_blog.file_type=='mp4'">
                                        <video controls>
                                            <source :src="single_blog.file" type="video/mp4">
                                        </video>
                                    </template>

                                    <template x-if="single_blog.file_type=='pdf'">
                                        <embed :src="single_blog.file" type="application/pdf"
                                            width="100%" height="600px" />
                                    </template>

                                </div>
                                <!-- .single-profile-img -->
                                <div class="single-profile-content blog-post-bottom">
                                    <div class="row m-0">
                                        <div class="col-xl-8 ps-0">
                                            <div
                                                class="profile-members-info profile-bottom ps-0 new-profile-rating">
                                                <span
                                                    class="profile-members-info-img profile-after-post">
                                                    <img :src="single_blog.author.avatar"
                                                        alt="single-profile-img-1"
                                                        class="img-responsive">
                                                </span>
                                                <span class="profile-members-info-name wh83-name"
                                                    x-text="single_blog.author.name">

                                                </span>
                                                <ul class="rating-view mt-1">
                                                    <template x-for="i in 5">
                                                        <div>
                                                            <li class="star-default active-rated"
                                                                x-show="i<=single_blog.ratings"><i
                                                                    class="fa-solid fa-star"></i></li>
                                                            <li class="star-default"
                                                                x-show="i>single_blog.ratings"><i
                                                                    class="fa-solid fa-star"></i></li>
                                                        </div>
                                                    </template>
                                                    <span class="rating-count ms-2"
                                                        x-text="single_blog.ratings"></span>
                                                </ul>
                                            </div>


                                        </div>
                                        <div class="col-xl-4 m-auto">
                                            <span class="profile-members-info-date top-10p"><i
                                                    class=" fa fa-solid fa-calendar-days"></i><span
                                                    x-text="getDate(single_blog)"></span></span>
                                        </div>
                                    </div>
                                </div>
                                <hr class="mb-0 mt-3" style="border-bottom: 1px solid #c3bfbf;">
                                <!-- .single-profile-content -->
                                <div class="single-profile-content">
                                    <h3><b x-text="single_blog.title"></b></h3>
                                    <p x-show="!single_blog.long_description"
                                        x-html="limitAndAddslashes(single_blog.description ,0, 250) "
                                        class="p-des-blog"></p><a :href="single_blog.details_url"
                                        class="text-success">..More</a>
                                    <p x-show="single_blog.long_description"
                                        x-html="single_blog.description">
                                    </p>
                                    <span x-show="single_blog.long_description"
                                        @click="single_blog.long_description=false"
                                        class="text-success">..less</span>
                                    <div>
                                        <span class="profile-members-info-comment"><i
                                                class="fa-solid fa-comments pe-2"></i><span
                                                x-text="single_blog.comments"></span> Comment</span>
                                    </div>
                                </div>
                                <div>
                        </template>
                    </div>
                </div>
        </div>
    </div>
</div>

</section>
</div>

<?php $content = ob_get_clean() ?>
<?php require layout_path('/landings/landing.phtml') ?>