<?php $title = "Registration" ?>

<?php ob_start() ?>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
<?php $top_js = ob_get_clean() ?>    

<?php ob_start() ?>
    <div x-data="data">
        <section class="bg-Profile banner-section all-sub-banner">
            <div class="page-header-overlay">
                <div class="auto-container">
                    <div class="row">
                        <div class="page-header">
                            <div class="page-title-registration">
                                <h2>Registration</h2>
                            </div>
                            <!-- .page-title -->
                            <div class="page-header-content">
                                    <ol class="breadcrumb">
                                        <li><a href="/">Home</a></li>
                            <li class="current ">Registration</li>
                            </ol>
                        </div>
                        <!-- .page-header-content -->
                    </div>
                    <!-- .page-header -->
                </div>
                <!-- .row -->
            </div>
            <!-- .container -->
    </div>
    <!-- .page-header-overlay -->
    </section>

    <section class="">
        <hr class="m-0">
        <div class="auto-container">
            <div class="single-profile">
                <div class="row">
                    <div class="col-lg-6 border-right-dashed">
                        <div class="card m-5 mb-0 mlr-0-res">
                            <div class="">
                                <div class="single-profile-img p-5 bg-gray-pic resp-pall">
                                    <img :src="avatar" alt="single-profile-img-1" class="img-responsive">
                                    <form action="" class="file-upload">
                                        <div class=" btn-greenradiousphoto">
                                            <input type="file" @change="setPreview($event.target.files)" id="img" name="img" accept="image/*" style="display: none;">
                                            <label for="img">Select Profile
                                                Image</label>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <span x-show="getError('avatar')" class="text-danger"><i class="fa-solid fa-circle-exclamation me-1"></i><span x-text="getError('avatar')"></span></span>
                    </div>
                    <!-- .col-lg-8 -->
                    <div class="col-lg-6">
                        <div class="single-experience-content p-5 ps-2 pe-2 resp-pal">
                            <div class="single-experience-option">
                                <form action="#">
                                    <div class="row m0-resp">
    
                                        <div class="col-md-6">
                                            <div class="single-form mt-4">
                                                <label class="form-label"> Name:<sup class="text-danger supc">*</sup></label>
                                                <input x-model="me.name" type="text" class="form-control">
                                            </div>

                                            <span x-show="getError('name')" class="text-danger"><i class="fa-solid fa-circle-exclamation me-1"></i><span x-text="getError('name')"></span></span>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="country-mobile-area">
                                                <label class="country-label" >+88</label>
                                                <div class="single-form mt-4">
                                                    <label class="form-label"> <span x-show="me.type=='organization'">Organization</span> Mobile
                                                        Number: <sup class="text-danger supc">*</sup></label>
                                                    <input x-model="me.phone" type="number" class="form-control pl70">
                                                </div>
                                                <span x-show="getError('phone')" class="text-danger"><i class="fa-solid fa-circle-exclamation me-1"></i><span x-text="getError('phone')"></span></span>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="single-form mt-4">
                                                <label class="form-label">Email:
                                                    <sup class="text-danger supc">*</sup></label>
                                                <input x-model="me.email" type="email" class="form-control">
                                            </div>
                                            <span x-show="getError('email')" class="text-danger"><i class="fa-solid fa-circle-exclamation me-1"></i><span x-text="getError('email')"></span></span>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="single-form mt-4">
                                                <label class="form-label">Password: <sup class="text-danger supc">*</sup></label>
                                                <input x-model="me.password" type="password" class="form-control">
                                            </div>

                                        </div>
                                        <div class="col-md-6">
                                            <div class="single-form mt-4">
                                                <label class="form-label">Confirm Password: <sup class="text-danger supc">*</sup></label>
                                                <input x-model="me.password_confirmation" type="password" class="form-control">
                                            </div>
                                        </div>

                                        <span x-show="getError('password')" class="text-danger"><i class="fa-solid fa-circle-exclamation me-1"></i><span x-text="getError('password')"></span></span>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- .col-md-4 -->
                </div>
                <!-- .row -->
            </div>
            <!-- .single-profile -->
        </div>
        <!-- .container -->

    </section>
    <hr class="m-0">
    <div class="row">
        <div class="d-flex mb-4">
            <button @click="update()" class="btn  btn-greenradious2 m-auto mt-5">Submit</button>
        </div>
    </div>
    </div>
<?php $content = ob_get_clean() ?>

<?php ob_start() ?>
    <script src="<?php echo assets('Assets/plugins/ckeditor/ckeditor.js') ?>"></script>
    <script src="<?php echo assets('Assets/js/useForm.js') ?>"></script>
    <script src="<?php echo assets('Assets/js/request.js') ?>"></script>
    <script>
        document.addEventListener('alpine:init', () => {
            Alpine.data('data', () => ({
                me: {
                    name:null,
                    phone:null,
                    email:null,
                    password:null,
                    password_confirmation:null
                },
                avatar: "<?php echo assets('Assets/images/profile/uploadimage.png') ?>",
                errors: {},

                getError(name) {
                    let error = this.errors[name]
                    if (error) {
                        return error[0].split('when')[0]
                    }
                },

                setPreview(files) {
                    this.me.avatar = files[0]
                    this.avatar = URL.createObjectURL(files[0])
                },


                update() {
                    post(
                        "/auth/registration",
                        formDataConverter(this.me, true), {
                            'ACCEPT': 'application/json',
                            'X-CSRF-TOKEN': "<?php echo csrf_token() ?>"
                        }, result => {
                            if (result && result.errors) {
                                this.errors = result.errors
                            }
                            console.log(result.status)
                            if (result.status) {
                                toasts.push({
                                    title: 'Success',
                                    content: `Registration Successful`,
                                    style: 'success',
                                    dismissAfter: '1s'
                                });
                                // window.location.assign("/");
                            } else {
                                toasts.push({
                                    title: 'Failed',
                                    content: `Registration Failed`,
                                    style: 'error',
                                    dismissAfter: '1s'
                                });
                            }
                        }
                    )
                },

                cleanErrorMessage(error, message) {
                    console.log(message)
                    if (error) {
                        return error.replace(message, '')
                    }
                }
            }))
        })
    </script>

<?php $js = ob_get_clean() ?>

<?php require layout_path('/landings/landing.phtml') ?>