<?php ob_start() ?>
<!DOCTYPE html>
<html lang="">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo $title??config('app.name')?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <?php echo $meta ?>
    <link href="<?php echo assets('Assets/css/bootstrap.css') ?>" rel="stylesheet">
    <link href="<?php echo assets('Assets/css/style.css') ?>" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo assets('Assets/images/icons/favicon.png') ?>">
    <!-- Responsive -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="<?php echo assets('Assets/css/responsive.css') ?>" rel="stylesheet">
    <?php echo $css ?>
    <?php echo $top_js ?>
    <link rel='stylesheet' href='https://unpkg.com/aos@2.3.0/dist/aos.css'>
</head>

<body>
    <div class="page-wrapper">

        <!-- Preloader -->
        <!-- <div class="preloader"></div> -->

        <!---Header---->

        <?php include layout_path('/landings/partials/header.phtml') ?>
        <!---end header---->

        <?php echo $content ?>

        <!---- Footer ---->
        <?php include layout_path('/landings/partials/footer.phtml') ?>
        <!----- End footer ---->

    </div>
    <!--End pagewrapper-->


    <!--Scroll to top-->
    <div class="scroll-to-top scroll-to-target" data-target=".main-header"><span class="fa fa-long-arrow-up"></span>
    </div>

    <div id="fb-customer-chat" class="fb-customerchat"></div>

    <script src="<?php echo assets('Assets/js/jquery.js') ?>"></script>
    <script src="<?php echo assets('Assets/js/owl.js') ?>"></script>
    <script src="<?php echo assets('Assets/js/bootstrap.min.js') ?>"></script>
    <script src="<?php echo assets('Assets/js/script.js') ?>"></script>
    <script src="<?php echo assets('Assets/js/toaster.js') ?>"></script>
    <script src="<?php echo assets('Assets/js/toaster.js') ?>"></script>
    <script>
        <?php if(session()->has('success')): ?>
            toasts.push({
                title: 'Success',
                content: `<?php echo session()->get('success') ?>`,
                style: 'success',
                dismissAfter: '1s'
            });
        <?php elseif(session()->has('error')): ?>
            toasts.push({
                title: 'Failed',
                content: `<?php echo session()->get('error') ?>`,
                style: 'error',
                dismissAfter: '1s'
            });
        <?php endif ?>
    </script>
    <script>
        $(document).on('click', '.pass-view', function(event) {
            var $open = $(this).children('.fa-eye');
            var $close = $(this).children('.fa-eye-slash');
            var $pass = $(this).siblings('.pass');
            if ($open.is(':visible')) {
                $close.show();
                $open.hide();
                $pass.attr('type', 'text');
            } else {
                $close.hide();
                $open.show();
                $pass.attr('type', 'password');
            }
        });
    </script>


    <?php echo $js ?>

    <script src='https://unpkg.com/aos@2.3.0/dist/aos.js'></script>
    <script>
        AOS.init({
            duration: 1200,
        })
    </script>
</body>

</html>

<?php $output = ob_get_clean() ?>
