
 <header class="main-header">


     <!-- Header Upper -->
     <div class="header-upper">
         <div class="auto-container clearfix menu-auto-container">
             <div class="row menu-m">
                 <div class="col-lg-12 p0-menu">
                     <!-- Logo -->
                     <div class="logo">
                         <a href="{{ route('home') }}"><img src="<?php echo assets('Assets/images/logo.svg') ?>"
                                 alt=""></a>
                     </div>

                     <!--Nav Outer-->
                     <div class="nav-outer clearfix">
                         <div class="nav-right">
                                 <!-- user-profile-drop-down -->
                                 <div class="user-profile-drop-down ms-1">
                                     <div class="btn-group">
                                         <button type="button" class="btn btn-danger dropdown-toggle"
                                             data-bs-toggle="dropdown" aria-expanded="false">
                                             <img src="{{ $user->avatar ? Storage::url($user->avatar) : asset('Assets/images/profile/uploadimage.png') }}"
                                                 alt="profile" class="img-responsive" />
                                             <span>shuvo</span>
                                         </button>
                                         <ul class="dropdown-menu mt-3">
                                                 <li><a class="dropdown-item" href="{{ route('profile') }}"><i
                                                             class="fa-solid fa-gauge me-2 text-gray"></i>Profile</a>
                                                 </li>

                                                 <li><a class="dropdown-item" href="{{ route('profile',['tab'=>'contacts'])  }}"><i
                                                             class="fa-regular fa-user me-2  text-gray"></i>My Contacts
                                                     </a>
                                                 </li>
                                                 <li><a class="dropdown-item" href="{{ route('jobListings') }}"><i
                                                             class="fa-regular fa-file me-2  text-gray"></i>Job
                                                         Listings</a>
                                                 </li>
                                             <li>
                                                 <hr class="dropdown-divider">
                                             </li>

                                             <li class="ps-3"> <a class="facebook img-circle  text-danger"
                                                     onclick="event.preventDefault();
                                   document.getElementById('logout-form').submit();"><i
                                                         class="fa fa-sign-out text-danger"></i>
                                                     Logout</a>
                                                 <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                                     style="display: none;">
                                                     @csrf
                                                 </form>
                                             </li>
                                         </ul>
                                     </div>
                                 </div>
                                 <!-- end user-profile-drop-down -->

                                 <li class="logon-li"><i class="fa-regular fa-user"></i><a
                                         href="{{ route('login') }}">Login</a></li>


                         </div>




                         <!-- Main Menu -->
                         <nav class="main-menu">

                             <div class="navbar-header">
                                 <!-- Toggle Button -->
                                 <button type="button" class="navbar-toggler d-lg-none collapsed"
                                     data-bs-toggle="collapse" data-bs-target="#bs-example-navbar-collapse-1"
                                     aria-controls="bs-example-navbar-collapse-1" aria-expanded="false">
                                     <span class="navbar-toggler-icon">
                                         <i class="fa fa-bars"></i>
                                     </span>
                                 </button>
                             </div>

                             <div class="navbar-collapse collapse clearfix" id="bs-example-navbar-collapse-1">
                                 <ul class="navigation">

                                     <li class="{{ Request::url() === route('home') ? 'current' : '' }}"><a
                                             href="{{ route('home') }}">HOME</a>

                                     </li>
                                     <li class="{{ Request::url() === route('aboutNetwork') ? 'current' : '' }}"><a
                                             href="{{ route('aboutNetwork') }}">ABOUT</a></li>

                                     <li class="{{ Request::url() === route('jobCategories') ? 'current' : '' }}">
                                         <a href="{{ route('jobCategories') }}">Opportunities</a>
                                     </li>
                                     <li class="{{ Request::url() === route('members') ? 'current' : '' }}">
                                         <a href="{{ route('members') }}">MEMBERS</a>
                                     </li>
                                     <li class="{{ Request::url() === route('resources') ? 'current' : '' }}"><a
                                             href="{{ route('resources') }}">Resources</a>

                                     </li>
                                     <li class="{{ Request::url() === route('news') ? 'current' : '' }}"><a
                                             href="{{ route('news') }}">News</a>

                                     </li>
                                     </li>
                                 </ul>
                             </div>
                         </nav>
                     </div>
                 </div>
             </div>


         </div>
     </div><!-- Header Top End -->

 </header><!--End Main Header -->
