<?php

namespace DoctrineProxies\__CG__\App\Authentication\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Module extends \App\Authentication\Entities\Module implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'associats' => [parent::class, 'associats', null, 8],
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null, 8],
        "\0".'*'."\0".'faker' => [parent::class, 'faker', null, 8],
        "\0".'*'."\0".'fillables' => [parent::class, 'fillables', null, 8],
        "\0".'*'."\0".'guarded' => [parent::class, 'guarded', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'permissions' => [parent::class, 'permissions', null, 8],
        "\0".'*'."\0".'persist' => [parent::class, 'persist', null, 8],
        "\0".'*'."\0".'slug' => [parent::class, 'slug', null, 8],
        "\0".'*'."\0".'timestamps' => [parent::class, 'timestamps', null, 8],
        "\0".'*'."\0".'title' => [parent::class, 'title', null, 8],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null, 8],
        'associats' => [parent::class, 'associats', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 8],
        'faker' => [parent::class, 'faker', null, 8],
        'fillables' => [parent::class, 'fillables', null, 8],
        'guarded' => [parent::class, 'guarded', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'permissions' => [parent::class, 'permissions', null, 8],
        'persist' => [parent::class, 'persist', null, 8],
        'slug' => [parent::class, 'slug', null, 8],
        'timestamps' => [parent::class, 'timestamps', null, 8],
        'title' => [parent::class, 'title', null, 8],
        'updatedAt' => [parent::class, 'updatedAt', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
